version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: public
    steps:

      # install git
      - run: apk update && apk add git

      # checkout the repository
      - checkout
      
      - run:
          name: "Initialize git submodules"
          command: git submodule init
      - run:
          name: "Update submodles"
          command: git submodule update
      
      # ls
      - run: ls -la 
      
       # ls
      - run: pwd
      
      # git status
      - run: git status
      
      # build with Hugo
      #- run: rm -rf public/* && HUGO_ENV=production hugo -v
      - run: hugo -v -d ./public -s .
      
      # ls
      - run: ls -la ./public
      
      # git status
      - run: git status
      
      # Go to the build folder
      - run: cd public/ && git add . && git config --global user.email "noreply@example.com" && git config --global user.name "CircleCI Bot" && git commit -m "Automated publish to JulienRouse.github.io [ci skip]" && git push origin master
       
       # ls
      - run: pwd
      
      # ls
      - run: ls -la
      
      # git status
      - run: git status
      
      # Add changes to git
      - run: git add .
      
      # Set some variables to add to the commit message
      - run: git config --global user.email "noreply@example.com" && git config --global user.name "CircleCI Bot"
      
      # Commit changes
      - run: git commit -m "Automated publish to JulienRouse.github.io [ci skip]" && git push origin master
      
      # Come back to root
      - run: cd ..
      