version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: public
    steps:

      # install git
      - run: apk update && apk add git

      # checkout the repository
      - checkout
      
      # build with Hugo
      #- run: rm -rf public/* && HUGO_ENV=production hugo -v
      - run: hugo -v
      
      # Go to the build folder
      - run: cd public/
      
      # Add changes to git
      - run: git add .
      
      # Set some variables to add to the commit message
      - run: git config --global user.email "noreply@example.com" && git config --global user.name "CircleCI Bot"
      
      # Commit changes
      - run: git commit -m "Automated publish to gh-pages [ci skip]" && git push origin master
      
      # Come back to root
      - run: cd ..
      